// src/utils/crypto.js

const crypto = require('crypto');
const EC = require('elliptic').ec;

// Initialize the secp256k1 elliptic curve (Standard for Bitcoin/Ethereum)
const ec = new EC('secp256k1');

/**
 * Computes the SHA-256 hash of any given inputs.
 * Sorts and stringifies objects to ensure consistent hashing regardless of input order.
 * * @param  {...any} inputs - Data to hash
 * @returns {string} - The hex string of the hash
 */
const cryptoHash = (...inputs) => {
    const hash = crypto.createHash('sha256');

    // Map inputs to strings, sort them so order doesn't change the hash, and join
    const stringifiedInputs = inputs
        .map(item => JSON.stringify(item))
        .sort()
        .join('');

    hash.update(stringifiedInputs);
    return hash.digest('hex');
};

/**
 * Verifies an elliptic curve digital signature.
 * * @param {Object} params
 * @param {string} params.publicKey - The sender's public key (hex string)
 * @param {string} params.dataHash - The hash of the data that was signed
 * @param {string} params.signature - The digital signature generated by the private key
 * @returns {boolean} - True if the signature is valid, false otherwise
 */
const verifySignature = ({ publicKey, dataHash, signature }) => {
    const keyFromPublic = ec.keyFromPublic(publicKey, 'hex');
    return keyFromPublic.verify(dataHash, signature);
};

module.exports = {
    ec,
    cryptoHash,
    verifySignature
};